[package]
name = "epub-mgr"
version = "0.1.0"
description = "A non-blocking EPUB finder"
authors = ["epub-mgr"]
edition = "2021"

[lib]
name = "epub_mgr_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
jwalk = "0.8"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
